---
# handlers file for ansible-consul
- name: reload consul
  service:
    name: "consul"
    state: "reloaded"
    sleep: 10
  become: true
  when: not ansible_check_mode

- name: restart consul
  service:
    name: "consul"
    state: "restarted"
    sleep: 10
  become: true
  when: not ansible_check_mode

- name: start consul
  service:
    name: "consul"
    state: "started"
  become: true
  when: not ansible_check_mode

- name: stop consul
  service:
    name: "consul"
    state: "stopped"
  become: true
  when: not ansible_check_mode

- name: restart dnsmasq
  service:
    name: "dnsmasq"
    state: "restarted"
  become: true
  when: not ansible_check_mode

- name: restart haproxy
  service:
    name: "haproxy"
    state: "restarted"
  become: true
  when: not ansible_check_mode

- name: restart keepalived
  service:
    name: "keepalived"
    state: "restarted"
  become: true
  when: not ansible_check_mode
