---
- name: install | downloading consul
  get_url:
    url: "{{ consul_dl_url }}/{{ consul_dl_file }}"
    dest: "/opt"
  become: true

- name: install | extracting consul binary
  unarchive:
    src: "/opt/{{ consul_dl_file }}"
    dest: "{{ consul_bin_path }}"
    copy: no
    creates: "{{ consul_bin_path }}/consul"
  become: true
  when: not ansible_check_mode
