---
- name: downloading consul
  get_url: url={{ consul_dl_url }}/{{ consul_dl_file }} dest=/opt

- name: extracting consul binary
  unarchive: src=/opt/{{ consul_dl_file }} dest={{ consul_bin_path }} copy=no creates={{ consul_bin_path }}/consul

- name: creating consul group
  group: name={{ consul_group }} state=present

- name: creating consul user
  user: name={{ consul_user }} group={{ consul_group }} system=yes

- name: creating consul configuration folders
  file: path={{ item }} owner=root group=root state=directory
  with_items:
    - '{{ consul_config_dir }}'
    - '{{ consul_config_dir }}/bootstrap'
    - '{{ consul_config_dir }}/client'
    - '{{ consul_config_dir }}/scripts'
    - '{{ consul_config_dir }}/server'

- name: creating consul data folder
  file: path={{ consul_data_dir }} owner={{ consul_user }} group={{ consul_group }} state=directory

- name: configuring consul master
  template: src=templates/etc/consul.d/bootstrap/config.json.j2 dest={{ consul_config_dir }}/bootstrap/config.json owner=root group=root mode=0644
  when: consul_master is defined and consul_master

- name: configuring consul servers
  template: src=templates/etc/consul.d/server/config.json.j2 dest={{ consul_config_dir }}/server/config.json owner=root group=root mode=0644
  when: consul_server is defined and consul_server

- name: configuriing consul clients
  template: src=templates/etc/consul.d/client/config.json.j2 dest={{ consul_config_dir }}/client/config.json owner=root group=root mode=0644
  when: consul_client is defined and consul_client

- name: creating consul client folders
  file: path={{ consul_home }} state=directory
  when: consul_client is defined and consul_client

- name: downloading consul ui
  get_url: url={{ consul_dl_url }}/{{ consul_ui_dl_file }} dest=/opt
  when: consul_client is defined and consul_client

- name: extracting consul ui
  unarchive: src=/opt/{{ consul_ui_dl_file }} dest={{ consul_home }} copy=no creates={{ consul_home }}/dist/index.html
  when: consul_client is defined and consul_client

- name: setting permissions on consul home folder
  file: path={{ consul_home }} owner={{ consul_user }} group={{ consul_group }} recurse=yes state=directory
  when: consul_client is defined and consul_client

- name: configuring consul init service
  template: src=templates/etc/init/consul.conf.j2 dest=/etc/init/consul.conf owner=root group=root mode=0644
  notify: restart consul
  when: (consul_server is defined and consul_server) or (consul_client is defined and consul_client)
