---
- name: install | download and extract consul
  unarchive:
    src: "{{ consul_dl_url }}/{{ consul_dl_file }}"
    dest: "{{ consul_bin_path }}"
    remote_src: True
    creates: "{{ consul_bin_path }}/consul"
  become: true
  when: not ansible_check_mode
