---
# tasks file for ansible-consul
- include: set_facts.yml
  tags:
    - consul_facts

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: install.yml

- include: config.yml

- include: services.yml

- include: clients.yml
  when: >
        ((groups[consul_clients_group] is defined and inventory_hostname
        in groups[consul_clients_group]))

- include: app_services.yml
  tags:
    - consul-app-services
  when: >
        ((groups[consul_clients_group] is defined and inventory_hostname
        in groups[consul_clients_group])) and consul_services is defined

- include: dnsmasq.yml
  when: >
        consul_enable_dnsmasq is defined and
        consul_enable_dnsmasq
