---
# tasks file for ansible-consul
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: config_consul.yml

- include: config_app_services.yml
  tags:
    - consul-app-services
  when: >
        consul_services is defined and
        inventory_hostname in groups[consul_clients_group]
