---
# tasks file for ansible-consul
- include: set_facts.yml
  tags:
    - consul_facts

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: install.yml

- include: config.yml

- include: services.yml

- include: clients.yml
  when: >
        (consul_cluster and
        inventory_hostname in groups[consul_clients_group]) or
        not consul_cluster

- include: app_services.yml
  tags:
    - consul-app-services
  when: >
        consul_services is defined and
        (consul_cluster and
        inventory_hostname in groups[consul_clients_group]) or
        not consul_cluster

- include: dnsmasq.yml
  when: >
        consul_enable_dnsmasq is defined and
        consul_enable_dnsmasq
